import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { prompt, baseImage } = await req.json();

    // Validate input
    if (!prompt || !baseImage) {
      return NextResponse.json(
        { error: "Missing prompt or base image." },
        { status: 400 }
      );
    }

    console.log("Sending prompt to llama3 backend:", { prompt });

    // Step 1: Call llama3 backend to process the prompt
    const llamaResponse = await fetch("http://localhost:11434/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "llama3:latest",
        prompt: prompt, // pass actual prompt here
        stream: false,
      }),
    });

    if (!llamaResponse.ok) {
      const errorText = await llamaResponse.text();
      console.error("llama3 backend error:", errorText);
      return NextResponse.json(
        { error: "llama3 API call failed." },
        { status: 500 }
      );
    }

    const llamaResult = await llamaResponse.json();

    // Adjust extraction to your llama3 response format, commonly 'response'
    const processedPrompt = llamaResult.response;

    if (!processedPrompt) {
      return NextResponse.json(
        { error: "No prompt generated by llama3." },
        { status: 500 }
      );
    }

    console.log("Processed prompt from llama3:", processedPrompt);

    // Step 2: Send processed prompt and base image to FastAPI backend
    const imageResponse = await fetch("http://127.0.0.1:8000/generate-image", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        prompt: processedPrompt,
        base_image: baseImage, // confirm key expected by FastAPI
      }),
    });

    if (!imageResponse.ok) {
      const errorText = await imageResponse.text();
      console.error("Image generation backend error:", errorText);
      return NextResponse.json(
        { error: "Image generation API call failed." },
        { status: 500 }
      );
    }

    const imageResult = await imageResponse.json();

    const styledImage =
      imageResult.generated_image || imageResult.image || imageResult.styledImageData;

    if (!styledImage) {
      return NextResponse.json(
        { error: "No image received from image generation backend." },
        { status: 500 }
      );
    }

    return NextResponse.json({ styledImageData: styledImage });
  } catch (error) {
    console.error("Unexpected error in API route:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
